version: "3.8"

services:
  # ========================================
  # Serveur Apache PHP
  # ========================================
  festivals-php:
    # Emplacement du dockerFile
    build:
      # Attention au contexte!
      context: .
      dockerfile: ./Docker/Dockerfile

    # Nom du container
    container_name: festivals-php
    ports:
      - 807:80

    volumes:
      # Dossier de l'application dans le DocumentRoot
      - ./app:/var/www/html

    # Logs
      - ./logs:/var/log/apache2

    networks:
      - phpFestivals


  # ========================================
  # Container avec MariaDb
  # ========================================
  festivals-db:
    container_name: festivals-db
    # Quelle image utilise t on? cf. https://hub.docker.com/search?q=&type=image
    image: mariadb:latest

    # Comportement en cas de plantage
    restart: unless-stopped

    # Volumes partagés entre l'hôte et le container
    volumes:
      - ./db_data:/var/lib/mysql
      # Script SQL utilisé au démarrage du container
      - ./DATA/festivals.sql:/docker-entrypoint-initdb.d/init.sql

    # Variables d'environnement définies dans le fichier .env
    # https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/
    environment:
      # Mot de passe de l'utilisateur root
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"

    # Redirection de ports
    ports:
      # La machine locale ouvre le port 3308 qui "pointe" vers le port 3306 du container
      - 3308:3306
    networks:
      - phpFestivals

  # ========================================
  # Container avec Adminer
  # ========================================
  festivals-adminer:
    container_name: festivals-adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8082:8080
    depends_on:
      - festivals-db
    networks:
      - phpFestivals

  # ========================================
  # Container avec PhpMyAdmin
  # ========================================
  festivals-phpmyadmin:
    container_name: festivals-phpmyadmin

    # Quelle image utilise t on? cf. https://hub.docker.com/search?q=&type=image
    image: phpmyadmin:latest

    # Comportement en cas de plantage
    restart: unless-stopped

    volumes:
      - ./Docker/config/pma_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./Docker/config/pma_config.php:/etc/phpmyadmin/config.user.inc.php

    # Variables d'environnement
    # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
    environment:
      # A quel hôte
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: "${DB_PORT}"
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASSWORD}"
      UPLOAD_LIMIT: 50M

    # Redirection de ports
    ports:
      # La machine locale ouvre le port 8081 qui "pointe" vers le port 80 du container
      - 8081:80

    # Dépendance du container PhpMyAdmin avec le container festivals-db
    depends_on:
      - festivals-db
    networks:
      - phpFestivals

networks:
  phpFestivals:
    driver: bridge
